import { useSiteContent } from "../cms/SiteContent";

export default function Localizacao() {
  const { content } = useSiteContent();
  const { location, contact } = content;
  const map = `https://www.google.com/maps?q=${encodeURIComponent(location.address)}&output=embed`;
  const whatsapp = `https://wa.me/${contact.whatsapp}?text=${encodeURIComponent("Olá! Quero agendar um horário.")}`;
  return <section className="section location-section" id="localizacao"><div className="container"><div className="section-intro" data-reveal><div><p className="section-eyebrow">{location.eyebrow}</p><h2 className="section-title">{location.title}</h2></div><p className="text-editorial text-lead">{location.description}</p></div><div className="location-grid" data-reveal-group><div className="map-wrap" data-reveal-item><iframe className="map-iframe" src={map} loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="Mapa do estúdio" allowFullScreen /></div><div className="panel" data-reveal-item><div className="panel-inner"><div className="panel-title"><h3>Endereço</h3></div><div className="kv"><div className="kv-row"><div className="kv-label">CEP</div><div className="kv-value">{location.zipCode}</div></div><div className="kv-row"><div className="kv-label">Rua</div><div className="kv-value">{location.street}</div></div><div className="kv-row"><div className="kv-label">Bairro</div><div className="kv-value">{location.neighborhood}</div></div><div className="kv-row"><div className="kv-label">Atendimento</div><div className="kv-value">{location.appointment}</div></div></div><div className="contact-actions"><a className="btn primary" href={whatsapp} target="_blank" rel="noreferrer">Agendar pelo WhatsApp</a><a className="btn secondary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location.address)}`} target="_blank" rel="noreferrer">Abrir no Google Maps</a></div></div></div></div></div></section>;
}
